version: "3"
services:
  node-app:
    image: api-server
    env_file: ./server/.env
    ports:
      - "1337:1337"
    networks:
      - social-media-app
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4-focal
    ports:
      - "27017:27017"
    networks:
      - social-media-app
    volumes: -mongo-data:/data/db
networks:
  social-media-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
